name: Kernel Config - A13 5.10

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:

jobs:
  build-kernels-a13-5-10:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "198"
            os_patch_level: "2024-01"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
