name: Kernel Config - A15 6.6

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:

jobs:
  build-kernels-a15:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "66"
            os_patch_level: "2025-02"
          - sub_level: "98"
            os_patch_level: "2025-08"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
