name: Kernel Config - A12 5.10

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:

jobs:
  build-kernels-a12:
    strategy:
      fail-fast: true
      matrix:
        include:
        - sub_level: "237"
          os_patch_level: "2025-06"
          revision: "r1"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}

